### check api health
GET http://localhost:4000/api/v1/health


### create new tickets
POSt http://localhost:4000/api/v1/tickets
Content-Type: application/json

{
    "username"  : "munira",
    "price" : 2500
}

### get all tickets
GET http://localhost:4000/api/v1/tickets


### get all tickets with filter
GET http://localhost:4000/api/v1/tickets?filter[username]=munira&sort=asc&limit=1&page=2


### get all tickets with sort , skip , limit
GET http://localhost:4000/api/v1/tickets?sort=asc&skip=2&limit=5



### get single ticket by id
GET http://localhost:4000/api/v1/tickets/j4yMP29Hp



### update or create new tickets
PUT http://localhost:4000/api/v1/tickets/ZMozMM-IO
Content-Type: application/json

{
    "price" : 100,
    "qnty" : 22
}



### delete single ticket by id
DELETE  http://localhost:4000/api/v1/tickets/ZMozMM-IO
